services:
  app:
    build: .
    container_name: gestor-horas
    ports:
      - "21000:8501"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: mis_horas
      DB_PASSWORD: mis_horas
      DB_NAME: mis_horas
    depends_on:
      - db
    restart: unless-stopped
    command: >
      streamlit run app.py 
      --server.address=0.0.0.0 
      --server.port=8501 
      --server.headless=true
      --server.enableCORS=false
      --server.enableXsrfProtection=false

  db:
    image: mysql:8.0
    container_name: mis_horas_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mis_horas
      MYSQL_USER: mis_horas
      MYSQL_PASSWORD: mis_horas
    ports:
      - "21003:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: